name: Build, Push to Docker Hub, and Deploy with Terraform

on:
  push:
    branches:
      - main  # Runs when code is pushed to the main branch

jobs:
  build-and-push:
    name: Build & Push Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker Image
        run: docker build -t slayerop15/portfolio-chatbot:latest .

      - name: Push Docker Image to Docker Hub
        run: docker push slayerop15/portfolio-chatbot:latest

  deploy:
    name: Deploy with Terraform
    runs-on: ubuntu-latest
    needs: build-and-push  # Runs only after the image is built and pushed

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: latest

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1 

      - name: Initialize Terraform
        run: terraform init
        working-directory: terraform

      - name: Plan Terraform Changes
        run: terraform plan
        working-directory: terraform

      - name: Apply Terraform Changes
        run: terraform apply -auto-approve
        working-directory: terraform
        env:
          TF_VAR_api_key: ${{ secrets.TF_VAR_api_key }}
