name: Destroy Infrastructure

on:
  workflow_dispatch:  # Manual trigger

jobs:
  destroy:
    name: Destroy Infrastructure
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: latest

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Download Terraform Outputs
        uses: actions/download-artifact@v4
        with:
          name: terraform-outputs
          path: terraform

      - name: Export API Key
        run: echo "TF_VAR_API_KEY=${{ secrets.TF_VAR_API_KEY }}" >> $GITHUB_ENV

      - name: Initialize Terraform
        run: terraform init
        working-directory: terraform

      - name: Plan Destroy
        run: terraform plan -destroy
        working-directory: terraform
        env:
          TF_VAR_API_KEY: ${{ secrets.TF_VAR_API_KEY }}

      - name: Confirm Destroy
        run: |
          echo "Are you sure you want to destroy all resources? Type 'yes' to confirm:"
          read confirmation
          if [ "$confirmation" != "yes" ]; then
            echo "Destroy cancelled"
            exit 1
          fi

      - name: Destroy Infrastructure
        run: terraform destroy -auto-approve
        working-directory: terraform
        env:
          TF_VAR_API_KEY: ${{ secrets.TF_VAR_API_KEY }}